package com.example.customtoggle.demo.toggle_helper

enum class ToggleType {
    // 1. System / App Settings
    WIFI, BLUETOOTH, DARK_MODE, LOCATION, MOBILE_DATA, AIRPLANE_MODE, DO_NOT_DISTURB,

    // 2. App Preferences
    NOTIFICATIONS, SOUND, VIBRATION, AUTO_UPDATE, SAVE_PASSWORD, BIOMETRICS, COMPACT_LAYOUT,

    // 3. Feature Controls
    GPS_TRACKING, BACKGROUND_SYNC, CLOUD_BACKUP, ADS_PERSONALIZATION, REMEMBER_ME, OFFLINE_MODE,

    // 4. Privacy & Security
    PRIVACY_LOCATION, CAMERA_MIC, ONLINE_STATUS, READ_RECEIPTS, TWO_FACTOR_AUTH, INCOGNITO_MODE,

    // 5. Media / Device Controls
    AUTOPLAY, WIFI_ONLY_DOWNLOAD, HIGH_QUALITY_STREAMING, BACKGROUND_PLAYBACK, SUBTITLES,
    CAMERA_FLASH, CAMERA_FILTERS,

    // 6. Smart Home / IoT
    LIGHT, FAN, AC_HEATER, DOOR_LOCK, SECURITY_ALARM, SMART_PLUG,

    // 7. User Profile / Account
    SHOW_EMAIL, PRIVATE_PROFILE, MESSAGE_NOTIFICATIONS, FRIEND_SUGGESTIONS, ACTIVE_STATUS,

    // 8. Developer / Advanced Settings
    DEBUG_MODE,
    LOGS,
    MOCK_LOCATIONS,
    BACKGROUND_TASKS,
    BATTERY_SAVER,
    STRICT_MODE,
    LAYOUT_BOUNDS,
    KEEP_AWAKE,
    GPU_PROFILING,

    // 9. Commerce / E-Commerce Apps
    ORDER_TRACKING, ONE_CLICK_CHECKOUT, OFFERS_NOTIFICATIONS, SAVE_CARD, WISHLIST_SYNC, PRICE_DROP_ALERTS,

    // 10. Fun / Creative Uses
    GAME_MODE, UNIT_SWITCH, LANGUAGE_SWITCH, THEME_TOGGLE, EMOJI_REACTIONS, PARENTAL_CONTROLS
}
